/*
 * Hello Genkit on Firebase Functions - Definitive Production Version v1.0
 * This version uses the authoritative pattern for deploying a Genkit flow
 * on Firebase, as generated by the official Firebase CLI tool.
 * It uses the 'onCallGenkit' trigger, which handles all HTTP and
 * body-parsing logic automatically. This is the stable bedrock.
 */

import {genkit, z} from "genkit";
import {vertexAI} from "@genkit-ai/vertexai";
import {onCallGenkit} from "firebase-functions/v2/https";

// Initialize Genkit with the Vertex AI plugin.
const ai = genkit({
  plugins: [
    vertexAI({location: "australia-southeast1"}),
  ],
});

// Define our simple "Hello World" flow.
// The logic is identical to our previous versions.
export const helloFlow = ai.defineFlow(
  {
    name: "helloFlow",
    inputSchema: z.object({name: z.string()}),
    outputSchema: z.string(),
  },
  async (input) => {
    console.log("[helloFlow] Input received:", input);
    return `Hello, ${input.name}!`;
  }
);

// Expose the 'helloFlow' to the internet using the 'onCallGenkit' trigger.
// This single line replaces the entire custom Express server.
export const hello = onCallGenkit({region: "australia-southeast1"}, helloFlow);
